export type SiteSettingCategory =
  | "general"
  | "seo"
  | "contact"
  | "social"
  | "email"
  | "notification"
  | "security"
  | "maintenance";

export type SiteInputType =
  | "text"
  | "textarea"
  | "number"
  | "boolean"
  | "url"
  | "email"
  | "json"
  | "image";

export interface ModuleLink {
  label: string;
  path: string;
  description: string;
}

export interface SiteSettingTemplate {
  key: string;
  label: string;
  description: string;
  category: SiteSettingCategory;
  inputType: SiteInputType;
  isPublic: boolean;
  defaultValue: string;
  module: ModuleLink;
  priority: "critical" | "high" | "normal";
  affectedAreas: string[];
  affectedPages: string[];
  verification: string[];
  rollback: string;
}

export const MODULE_SHORTCUTS: ModuleLink[] = [
  {
    label: "Marka & Kimlik",
    path: "/admin/branding",
    description: "Logo, favicon, site adı ve marka metinleri",
  },
  {
    label: "Web Kontrol Merkezi",
    path: "/admin/web-control",
    description: "Hero, menüler, footer, bölüm sıraları",
  },
  {
    label: "Ana Sayfa Yönetimi",
    path: "/admin/homepage",
    description: "Home bölüm sırası ve showcase içerikleri",
  },
  {
    label: "Özellik Yönetimi",
    path: "/admin/features",
    description: "Webde hangi özelliklerin açık olduğunu yönet",
  },
  {
    label: "SEO Yönetimi",
    path: "/admin/seo",
    description: "Sayfa bazlı SEO ve global meta ayarları",
  },
];

export const SITE_SETTING_TEMPLATES: SiteSettingTemplate[] = [
  {
    key: "site_name",
    label: "Site Adı",
    description: "Header, footer ve SEO başlıklarında görünen marka adı",
    category: "general",
    inputType: "text",
    isPublic: true,
    defaultValue: "Lumiohan",
    module: MODULE_SHORTCUTS[0],
    priority: "high",
    affectedAreas: ["Header", "Footer", "SEO başlıkları"],
    affectedPages: ["/", "/blog", "/gallery"],
    verification: [
      "Header logosu yanında yeni isim görünüyor mu kontrol et",
      "Footer altındaki copyright metnini kontrol et",
      "Ana sayfa title etiketini DevTools ile doğrula",
    ],
    rollback: "Önceki site adını geri yaz ve kaydet.",
  },
  {
    key: "site_logo_url",
    label: "Site Logosu",
    description: "Desktop ve mobil header logosu",
    category: "general",
    inputType: "image",
    isPublic: true,
    defaultValue: "/Logo-01.png",
    module: MODULE_SHORTCUTS[0],
    priority: "high",
    affectedAreas: ["Desktop header", "Mobil header"],
    affectedPages: ["/", "tüm sayfalar"],
    verification: [
      "Desktop header logosunu yenile ve görüntüyü kontrol et",
      "Mobil header'da logo ölçeklemesini kontrol et",
      "404 veren görsel URL'si olmadığını doğrula",
    ],
    rollback: "Önceki logo URL'sini geri yükle.",
  },
  {
    key: "site_favicon_url",
    label: "Favicon",
    description: "Tarayıcı sekme ikonu ve SEO head icon linkleri",
    category: "general",
    inputType: "image",
    isPublic: true,
    defaultValue: "/Logo-02.png",
    module: MODULE_SHORTCUTS[0],
    priority: "normal",
    affectedAreas: ["Browser tab", "SEO icon tags"],
    affectedPages: ["tüm sayfalar"],
    verification: [
      "Tarayıcı sekmesini hard refresh ile yenile",
      "link[rel='icon'] değerini DevTools'ta doğrula",
      "Mobil safari icon güncellemesini kontrol et",
    ],
    rollback: "Önceki favicon URL'sine dön.",
  },
  {
    key: "site_tagline",
    label: "Site Sloganı",
    description: "Marka sloganı ve tanıtım metinlerinde kullanılır",
    category: "general",
    inputType: "text",
    isPublic: true,
    defaultValue: "",
    module: MODULE_SHORTCUTS[0],
    priority: "normal",
    affectedAreas: ["Branding metinleri"],
    affectedPages: ["/", "/login", "/register"],
    verification: [
      "Sloganın göründüğü alanları sayfada kontrol et",
      "Uzun metinde taşma olup olmadığını doğrula",
    ],
    rollback: "Eski slogan metnini geri yaz.",
  },
  {
    key: "site_description",
    label: "Site Açıklaması",
    description: "SEO açıklamaları için temel açıklama metni",
    category: "seo",
    inputType: "textarea",
    isPublic: true,
    defaultValue: "",
    module: MODULE_SHORTCUTS[0],
    priority: "high",
    affectedAreas: ["Meta description fallback"],
    affectedPages: ["/", "/blog", "/gallery"],
    verification: [
      "Meta description tag içeriğini kontrol et",
      "Paylaşım önizlemelerinde açıklama metnini doğrula",
    ],
    rollback: "Önceki açıklamayı geri yükle.",
  },
  {
    key: "web_ui_config",
    label: "Web UI Konfigürasyonu",
    description:
      "Hero, menüler, home section ve footer sıralama/görünürlük JSON'u",
    category: "general",
    inputType: "json",
    isPublic: true,
    defaultValue: "{}",
    module: MODULE_SHORTCUTS[1],
    priority: "critical",
    affectedAreas: ["Home düzeni", "Header menü", "Mobile nav", "Footer"],
    affectedPages: ["/", "header görünen tüm sayfalar"],
    verification: [
      "Home bölüm sıralarını desktop ve mobilde kontrol et",
      "Header menü sırası beklendiği gibi mi doğrula",
      "Footer link sırasını ve içerikleri test et",
    ],
    rollback: "Geçerli çalışan JSON yedeğini geri yapıştırıp kaydet.",
  },
  {
    key: "maintenance_mode_enabled",
    label: "Bakım Modu",
    description: "Admin dışı kullanıcılar için siteyi bakım ekranına alır",
    category: "maintenance",
    inputType: "boolean",
    isPublic: true,
    defaultValue: "false",
    module: MODULE_SHORTCUTS[3],
    priority: "critical",
    affectedAreas: ["Genel erişim kontrolü"],
    affectedPages: ["tüm route'lar"],
    verification: [
      "Admin dışı hesapla anasayfaya gir ve bakım ekranı gör",
      "Admin hesapla admin panel erişiminin devam ettiğini doğrula",
    ],
    rollback: "Değeri false yap ve kaydet.",
  },
  {
    key: "maintenance_message",
    label: "Bakım Mesajı",
    description: "Bakım ekranında kullanıcıya gösterilen mesaj",
    category: "maintenance",
    inputType: "textarea",
    isPublic: true,
    defaultValue: "Sistem bakımda, lütfen daha sonra tekrar deneyin.",
    module: MODULE_SHORTCUTS[3],
    priority: "high",
    affectedAreas: ["Maintenance sayfası metni"],
    affectedPages: ["maintenance görünümü"],
    verification: ["Bakım ekranında güncel mesajın çıktığını doğrula"],
    rollback: "Önceki mesajı geri yaz.",
  },
  {
    key: "registration_enabled",
    label: "Kayıt Açık",
    description: "Yeni kullanıcı kayıt route'unu açar/kapatır",
    category: "security",
    inputType: "boolean",
    isPublic: true,
    defaultValue: "true",
    module: MODULE_SHORTCUTS[3],
    priority: "high",
    affectedAreas: ["Auth route kontrolü"],
    affectedPages: ["/register"],
    verification: [
      "Kapatınca /register erişiminin engellendiğini doğrula",
      "Açınca kayıt akışının tekrar çalıştığını test et",
    ],
    rollback: "Değeri eski haline getir (genelde true).",
  },
  {
    key: "referral_system_enabled",
    label: "Referans Sistemi Açık",
    description: "Referans kazanım akışını açar/kapatır",
    category: "general",
    inputType: "boolean",
    isPublic: true,
    defaultValue: "true",
    module: MODULE_SHORTCUTS[3],
    priority: "normal",
    affectedAreas: ["Referral servisleri", "Kazanım akışı"],
    affectedPages: ["profil/referans alanları"],
    verification: [
      "Referans kodu kullanımı sonrası kredi akışını kontrol et",
      "Kapatıldığında referans işlemlerinin tetiklenmediğini doğrula",
    ],
    rollback: "Eski değeri geri yaz.",
  },
  {
    key: "referral_show_on_dashboard",
    label: "Dashboard Referans Kartı",
    description: "Kullanıcı panelinde referans kartını göster/gizle",
    category: "general",
    inputType: "boolean",
    isPublic: true,
    defaultValue: "true",
    module: MODULE_SHORTCUTS[3],
    priority: "normal",
    affectedAreas: ["Kullanıcı dashboard görünümü"],
    affectedPages: ["/profile"],
    verification: ["Profil/dashboard üzerinde kart görünürlüğünü kontrol et"],
    rollback: "Önceki değere dön.",
  },
  {
    key: "image_generation_enabled",
    label: "Görsel Üretim Açık",
    description: "Görsel üretim sayfası ve ilgili menüleri yönetir",
    category: "general",
    inputType: "boolean",
    isPublic: true,
    defaultValue: "true",
    module: MODULE_SHORTCUTS[3],
    priority: "critical",
    affectedAreas: ["Header/Mobile menü", "Create akışı", "Home araçları"],
    affectedPages: ["/generate", "/"],
    verification: [
      "Header ve mobil menüde generate linkini kontrol et",
      "/generate route erişimini doğrula",
      "Home tool kartında görünürlüğü test et",
    ],
    rollback: "Değeri eski haline al (genelde true).",
  },
  {
    key: "video_generation_enabled",
    label: "Video Üretim Açık",
    description: "Video ve motion control akışlarını yönetir",
    category: "general",
    inputType: "boolean",
    isPublic: true,
    defaultValue: "true",
    module: MODULE_SHORTCUTS[3],
    priority: "critical",
    affectedAreas: ["Header/Mobile menü", "Home video bölümleri"],
    affectedPages: ["/video-generate", "/motion-control", "/"],
    verification: [
      "Video route erişimini doğrula",
      "Home video section görünümünü kontrol et",
      "Menü linklerinin duruma göre gizlenmesini test et",
    ],
    rollback: "Değeri eski haline al.",
  },
  {
    key: "ai_influencer_enabled",
    label: "AI Influencer Açık",
    description: "AI influencer modülü route ve menü görünürlüğü",
    category: "general",
    inputType: "boolean",
    isPublic: true,
    defaultValue: "true",
    module: MODULE_SHORTCUTS[3],
    priority: "high",
    affectedAreas: ["Header/Mobile menü", "Home araç kartları"],
    affectedPages: ["/ai-influencer", "/"],
    verification: [
      "Route erişimini kontrol et",
      "Header/mobile menüde link görünürlüğünü doğrula",
    ],
    rollback: "Önceki değeri geri yaz.",
  },
  {
    key: "upscale_enabled",
    label: "Upscale Açık",
    description: "Upscale modülünü menü ve route üzerinde açar/kapatır",
    category: "general",
    inputType: "boolean",
    isPublic: true,
    defaultValue: "true",
    module: MODULE_SHORTCUTS[3],
    priority: "high",
    affectedAreas: ["Header/Mobile menü", "Home araç kartları"],
    affectedPages: ["/upscale", "/"],
    verification: ["Upscale route ve menü linkini kontrol et"],
    rollback: "Önceki değere dön.",
  },
  {
    key: "audio_generation_enabled",
    label: "Audio Generate Açık",
    description: "Audio üretim modülü route ve menü görünürlüğü",
    category: "general",
    inputType: "boolean",
    isPublic: true,
    defaultValue: "true",
    module: MODULE_SHORTCUTS[3],
    priority: "normal",
    affectedAreas: ["Header/Mobile menü"],
    affectedPages: ["/audio-generate"],
    verification: ["Audio route ve menü link görünürlüğünü kontrol et"],
    rollback: "Eski değeri geri yaz.",
  },
  {
    key: "music_generation_enabled",
    label: "Music Generate Açık",
    description: "Music üretim modülü route ve menü görünürlüğü",
    category: "general",
    inputType: "boolean",
    isPublic: true,
    defaultValue: "true",
    module: MODULE_SHORTCUTS[3],
    priority: "normal",
    affectedAreas: ["Header/Mobile menü"],
    affectedPages: ["/music-generate"],
    verification: ["Music route ve menü link görünürlüğünü kontrol et"],
    rollback: "Eski değeri geri yaz.",
  },
  {
    key: "gallery_enabled",
    label: "Galeri Açık",
    description: "Galeri route ve galeri bloklarının görünürlüğü",
    category: "general",
    inputType: "boolean",
    isPublic: true,
    defaultValue: "true",
    module: MODULE_SHORTCUTS[3],
    priority: "high",
    affectedAreas: ["Header/Mobile menü", "Home gallery", "Bottom nav"],
    affectedPages: ["/gallery", "/"],
    verification: [
      "Galeri route erişimini doğrula",
      "Home gallery section görünürlüğünü kontrol et",
    ],
    rollback: "Değeri eski haline getir.",
  },
  {
    key: "blog_enabled",
    label: "Blog Açık",
    description: "Blog route ve blog linklerini yönetir",
    category: "general",
    inputType: "boolean",
    isPublic: true,
    defaultValue: "true",
    module: MODULE_SHORTCUTS[3],
    priority: "high",
    affectedAreas: ["Header/Mobile menü", "Footer link"],
    affectedPages: ["/blog", "/blog/:slug"],
    verification: [
      "Blog liste ve detay route'larını kontrol et",
      "Menü ve footer link görünürlüğünü doğrula",
    ],
    rollback: "Önceki değeri geri yaz.",
  },
  {
    key: "community_enabled",
    label: "Topluluk Açık",
    description: "Community characters route ve home bölüm görünürlüğü",
    category: "general",
    inputType: "boolean",
    isPublic: true,
    defaultValue: "true",
    module: MODULE_SHORTCUTS[3],
    priority: "high",
    affectedAreas: ["Home community block", "Mobile bottom nav"],
    affectedPages: ["/community-characters", "/"],
    verification: [
      "Community route erişimini kontrol et",
      "Home ve bottom nav görünürlüğünü doğrula",
    ],
    rollback: "Eski değere dön.",
  },
  {
    key: "signup_bonus_credits",
    label: "Kayıt Bonus Kredisi",
    description: "Yeni kullanıcıya verilen başlangıç kredi miktarı",
    category: "general",
    inputType: "number",
    isPublic: true,
    defaultValue: "25",
    module: MODULE_SHORTCUTS[3],
    priority: "high",
    affectedAreas: ["Register ekranı", "ilk kredi dağıtımı"],
    affectedPages: ["/register"],
    verification: [
      "Register ekranındaki bonus metnini kontrol et",
      "Yeni kullanıcıda kredi miktarını doğrula",
    ],
    rollback: "Önceki bonus değerini geri yaz.",
  },
  {
    key: "packages_bonus_message",
    label: "Paket Bonus Mesajı Açık",
    description: "Paket bonus mesajını göster/gizle",
    category: "general",
    inputType: "boolean",
    isPublic: true,
    defaultValue: "true",
    module: MODULE_SHORTCUTS[3],
    priority: "normal",
    affectedAreas: ["Packages banner metni"],
    affectedPages: ["/packages"],
    verification: ["Packages sayfasında bonus mesaj görünürlüğünü kontrol et"],
    rollback: "Eski değeri geri yaz.",
  },
  {
    key: "packages_bonus_text",
    label: "Paket Bonus Metni",
    description: "Paketler sayfasındaki bonus metni",
    category: "general",
    inputType: "text",
    isPublic: true,
    defaultValue: "Büyük paketlerde %35'e varan bonus!",
    module: MODULE_SHORTCUTS[3],
    priority: "normal",
    affectedAreas: ["Packages bonus içerik"],
    affectedPages: ["/packages"],
    verification: ["Packages sayfasında metni ve taşma durumunu kontrol et"],
    rollback: "Önceki metni geri yaz.",
  },
  {
    key: "packages_validity_message",
    label: "Paket Geçerlilik Mesajı Açık",
    description: "Paket geçerlilik mesajını göster/gizle",
    category: "general",
    inputType: "boolean",
    isPublic: true,
    defaultValue: "true",
    module: MODULE_SHORTCUTS[3],
    priority: "normal",
    affectedAreas: ["Packages validity metni"],
    affectedPages: ["/packages"],
    verification: ["Packages sayfasında validity görünürlüğünü kontrol et"],
    rollback: "Önceki değeri geri yükle.",
  },
  {
    key: "packages_validity_text",
    label: "Paket Geçerlilik Metni",
    description: "Paket geçerlilik satırındaki açıklama metni",
    category: "general",
    inputType: "text",
    isPublic: true,
    defaultValue: "Sınırsız geçerlilik süresi",
    module: MODULE_SHORTCUTS[3],
    priority: "normal",
    affectedAreas: ["Packages validity içerik"],
    affectedPages: ["/packages"],
    verification: ["Packages sayfasında güncel metni kontrol et"],
    rollback: "Eski metni geri yaz.",
  },
  {
    key: "email_notifications_enabled",
    label: "E-posta Bildirimleri Açık",
    description: "Sistem e-posta bildirimlerinin genel anahtarı",
    category: "notification",
    inputType: "boolean",
    isPublic: true,
    defaultValue: "true",
    module: MODULE_SHORTCUTS[3],
    priority: "normal",
    affectedAreas: ["Mail bildirim tetikleyicileri"],
    affectedPages: ["arka plan süreçleri"],
    verification: ["Bildirim tetikleyen bir aksiyon sonrası mail kontrolü yap"],
    rollback: "Önceki değere geri dön.",
  },
  {
    key: "push_notifications_enabled",
    label: "Push Bildirimleri Açık",
    description: "Tarayıcı push bildirim mekanizmasının genel anahtarı",
    category: "notification",
    inputType: "boolean",
    isPublic: true,
    defaultValue: "false",
    module: MODULE_SHORTCUTS[3],
    priority: "normal",
    affectedAreas: ["Web push servisleri"],
    affectedPages: ["notification izin akışı"],
    verification: ["Push izin ve gönderim testini staging ortamında doğrula"],
    rollback: "Değeri eski haline al.",
  },
  {
    key: "credit_cost_1k",
    label: "1K Kredi Maliyeti",
    description: "1K kalite üretiminde kredi tüketim parametresi",
    category: "general",
    inputType: "number",
    isPublic: true,
    defaultValue: "1",
    module: MODULE_SHORTCUTS[3],
    priority: "high",
    affectedAreas: ["Fiyatlandırma hesapları", "üretim maliyeti"],
    affectedPages: ["/generate", "/video-generate"],
    verification: ["1K üretim yapıp harcanan kredi miktarını doğrula"],
    rollback: "Önceki sayı değerini geri yaz.",
  },
  {
    key: "credit_cost_2k",
    label: "2K Kredi Maliyeti",
    description: "2K kalite üretiminde kredi tüketim parametresi",
    category: "general",
    inputType: "number",
    isPublic: true,
    defaultValue: "2",
    module: MODULE_SHORTCUTS[3],
    priority: "high",
    affectedAreas: ["Fiyatlandırma hesapları", "üretim maliyeti"],
    affectedPages: ["/generate", "/video-generate"],
    verification: ["2K üretim yapıp harcanan kredi miktarını doğrula"],
    rollback: "Önceki sayı değerini geri yaz.",
  },
  {
    key: "credit_cost_4k",
    label: "4K Kredi Maliyeti",
    description: "4K kalite üretiminde kredi tüketim parametresi",
    category: "general",
    inputType: "number",
    isPublic: true,
    defaultValue: "4",
    module: MODULE_SHORTCUTS[3],
    priority: "high",
    affectedAreas: ["Fiyatlandırma hesapları", "üretim maliyeti"],
    affectedPages: ["/generate", "/video-generate"],
    verification: ["4K üretim yapıp harcanan kredi miktarını doğrula"],
    rollback: "Önceki sayı değerini geri yaz.",
  },
];
