CREATE TABLE `globalSeoConfig` (
	`id` int AUTO_INCREMENT NOT NULL,
	`siteName` varchar(100) DEFAULT 'NanoInf',
	`siteTagline` varchar(200),
	`defaultLanguage` varchar(10) DEFAULT 'tr',
	`defaultMetaTitle` varchar(70),
	`defaultMetaDescription` varchar(160),
	`defaultMetaKeywords` text,
	`defaultOgImage` text,
	`facebookAppId` varchar(50),
	`defaultTwitterSite` varchar(50),
	`defaultTwitterCreator` varchar(50),
	`googleVerification` varchar(100),
	`bingVerification` varchar(100),
	`yandexVerification` varchar(100),
	`pinterestVerification` varchar(100),
	`googleAnalyticsId` varchar(50),
	`googleTagManagerId` varchar(50),
	`facebookPixelId` varchar(50),
	`robotsTxtContent` text,
	`sitemapEnabled` boolean NOT NULL DEFAULT true,
	`sitemapLastGenerated` timestamp,
	`organizationName` varchar(200),
	`organizationLogo` text,
	`organizationUrl` varchar(500),
	`contactEmail` varchar(200),
	`contactPhone` varchar(50),
	`socialLinks` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `globalSeoConfig_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `seoSettings` (
	`id` int AUTO_INCREMENT NOT NULL,
	`pageSlug` varchar(100) NOT NULL,
	`pageName` varchar(200) NOT NULL,
	`metaTitle` varchar(70),
	`metaDescription` varchar(160),
	`metaKeywords` text,
	`canonicalUrl` varchar(500),
	`ogTitle` varchar(95),
	`ogDescription` varchar(200),
	`ogImage` text,
	`ogType` enum('website','article','product','profile') DEFAULT 'website',
	`ogLocale` varchar(10) DEFAULT 'tr_TR',
	`twitterCard` enum('summary','summary_large_image','app','player') DEFAULT 'summary_large_image',
	`twitterTitle` varchar(70),
	`twitterDescription` varchar(200),
	`twitterImage` text,
	`twitterSite` varchar(50),
	`twitterCreator` varchar(50),
	`robotsIndex` boolean NOT NULL DEFAULT true,
	`robotsFollow` boolean NOT NULL DEFAULT true,
	`robotsNoArchive` boolean NOT NULL DEFAULT false,
	`robotsNoSnippet` boolean NOT NULL DEFAULT false,
	`structuredData` text,
	`priority` decimal(2,1) DEFAULT '0.5',
	`changeFrequency` enum('always','hourly','daily','weekly','monthly','yearly','never') DEFAULT 'weekly',
	`isActive` boolean NOT NULL DEFAULT true,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `seoSettings_id` PRIMARY KEY(`id`),
	CONSTRAINT `seoSettings_pageSlug_unique` UNIQUE(`pageSlug`)
);
